server:
  port: 8081
spring:
  cloud:
    config: 
      server:
        git:
          default-label: eureka
          uri: https://github.com/marioog97/microservicios-crs
          search-paths: config-data
  application: 
    name: config.service